// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jecuaqdjimmqyflfokqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplY3VhcWRqaW1tcXlmbGZva3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODI5MzIsImV4cCI6MjA3NDY1ODkzMn0.423JRru0aecJY72nY-rffkaNBM3kaCLOlMwM9YM5Tgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});